# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'BTG Mobile Challange' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for BTG Mobile Challange

  target 'BTG Mobile ChallangeTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
  end

end
